---
- hosts: all
  become: yes
  vars_files:
    - ./vpn_vars/oci-tunnel1.yml
    - ./vpn_vars/oci-tunnel2.yml
    - ./tf-ansible-extra-vars.yml

  tasks:

  - name: install libreswan
    yum:
      name: libreswan
      state: installed

  - name: install quagga
    yum:
      name: quagga
      state: installed

  - name: write the vpn config file
    template: src=libreswan.j2 dest=/etc/ipsec.d/oci-vpn-tunnels.conf
    become: true

  - name: write the vpn secrets file
    template: src=libreswan_secrets.j2 dest=/etc/ipsec.d/oci-vpn-secrets.secrets
    become: true

  - name: Apply Permissions for quagga
    shell: chmod -R 777 /etc/quagga
    become: true

  - name: Enable Ibr_netfilter IPv4
    copy:
      dest: /etc/sysctl.conf
      content: |
        net.ipv4.ip_forward = 1
        net.ipv4.conf.default.rp_filter = 0
        net.ipv4.conf.all.rp_filter = 0
        net.ipv4.conf.all.send_redirects = 0
        net.ipv4.conf.default.send_redirects = 0
        net.ipv4.icmp_ignore_bogus_error_responses = 1
        net.ipv4.conf.default.log_martians = 0
        net.ipv4.conf.all.log_martians = 0
        net.ipv4.conf.default.accept_source_route = 0
        net.ipv6.conf.default.accept_source_route = 0
        net.ipv4.conf.all.accept_redirects = 0
        net.ipv6.conf.all.accept_redirects = 0
        net.ipv4.conf.default.accept_redirects = 0
        net.ipv6.conf.default.accept_redirects = 0
    
  - name: Apply Persistent IPv4 Forwarding
    shell: sudo sysctl -p

  - name: Disable Selinux
    shell: sudo setenforce 0

  - name: Disable Firewalld
    shell: sudo systemctl stop firewalld

  - name: ensure ipsec is running
    service: name=ipsec state=started
    become: yes

  - name: Apply Persistent IPSEC connection
    shell: systemctl enable ipsec.service
    become: yes

  - name: Activate the tunnel
    shell: "{{ item }}" 
    with_items:
      - ipsec auto --start oci-tunnel1
      - ipsec auto --add oci-tunnel1
      - ipsec auto --up oci-tunnel1
      - ipsec auto --start oci-tunnel2
      - ipsec auto --add oci-tunnel2
      - ipsec auto --up oci-tunne2
    become: yes
    ignore_errors: yes

  - name: write the guagga file
    template: src=zebra.conf.j2 dest=/etc/quagga/zebra.conf
    become: true

  - name: write the bgpd file
    template: src=bgpd.conf.j2 dest=/etc/quagga/bgpd.conf
    become: true

  - name: ensure zebra is running
    service: name=zebra state=started
    become: yes

  - name: Apply Persistent zebra
    shell: systemctl enable zebra.service
    become: yes
  
  - name: ensure bgpd is running
    service: name=bgpd =started
    become: yes

  - name: Apply Persistent bgpd
    shell: systemctl enable bgpd.service
    become: yes

  - name: Restart IPSEC
    shell: ipsec restart
    become: yes