---
#Name for the VPN Connetion
conn_name_tunnel1: oci-tunnel1

#Connection settings
tunnel1_cidr: "10.10.10.100/30"
left: "{{ cpe_local_ip }}"
right: "{{ oci_headend1 }}"
vti1: "vti1"
oci_vcn_cidr: "{{ oci_vcn_cidr }}"
tunnel1_leftvti: "10.10.100.101/30"
#PSK to be used. 
vpn_psk: "{{ shared_secret_psk }}"

